# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
  # # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
  # # If you'd like to customize it, uncomment and adjust the pipeline.
  # # See https://rasa.com/docs/rasa/tuning-your-model for more information.
  - name: WhitespaceTokenizer
    intent_tokenization_flag: True
    intent_split_symbol: '+'
  #   - name: RegexFeaturizer
  #   - name: LexicalSyntacticFeaturizer
  #   - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  #   - name: EntitySynonymMapper
  #   - name: ResponseSelector
  #     epochs: 100
  #     constrain_similarities: true
  #   - name: FallbackClassifier
  #     threshold: 0.3
  #     ambiguity_threshold: 0.1
  - name: 'DucklingEntityExtractor'
    # url of the running duckling server
    url: 'http://127.0.0.1:5000'
    # dimensions to extract
    dimensions: ['time', 'amount-of-money']
    # allows you to configure the locale, by default the language is
    # used
    locale: 'EN'
    # if not set the default timezone of Duckling is going to be used
    # needed to calculate dates from relative expressions like "tomorrow"
    timezone: 'India/Calcutta'
    # Timeout for receiving response from http url of the running duckling server
    # if not set the default timeout of duckling http url is set to 3 seconds.
    timeout: 3

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  # # No configuration for policies was provided. The following default policies were used to train your model.
  # # If you'd like to customize them, uncomment and adjust the policies.
  # # See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
  - name: 'RulePolicy'
    core_fallback_threshold: 0.3
    core_fallback_action_name: action_default_fallback
    enable_fallback_prediction: true
    restrict_rules: true
    check_for_contradictions: true
  # - name: UnexpecTEDIntentPolicy
  #   max_history: 5
  #   epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
